import { QuizLevel } from './quiz.model';

export const QUIZ_DATA: QuizLevel[] = [
    {
        level: 1,
        difficulty: 'Easy',
        questions: [
            { id: 1, text: "How many months are in the Islamic calendar?", options: ["10", "11", "12", "13"], correctAnswer: 2, explanation: "The Islamic calendar consists of 12 months, just like the Gregorian calendar." },
            { id: 2, text: "Which direction do Muslims face during prayer?", options: ["East", "West", "The Kaaba", "Jerusalem"], correctAnswer: 2, explanation: "Muslims face the Kaaba in Makkah, which is known as the Qibla." },
            { id: 3, text: "What is the first month of the Islamic calendar?", options: ["Ramadan", "Muharram", "Shawwal", "Dhul-Hijjah"], correctAnswer: 1, explanation: "Muharram is the first month of the Hijri calendar." },
            { id: 4, text: "How many pillars of Islam are there?", options: ["3", "4", "5", "6"], correctAnswer: 2, explanation: "There are five pillars: Shahada, Salah, Zakat, Sawm, and Hajj." },
            { id: 5, text: "What is the name of the holy book of Islam?", options: ["Torah", "Gospel", "Psalms", "Quran"], correctAnswer: 3, explanation: "The Quran is the central religious text of Islam." },
            { id: 6, text: "How many times a day do Muslims perform obligatory prayers?", options: ["3", "4", "5", "7"], correctAnswer: 2, explanation: "Muslims perform five obligatory prayers (Salah) daily." },
            { id: 7, text: "Which prophet received the Quran?", options: ["Ibrahim", "Musa", "Isa", "Muhammad (PBUH)"], correctAnswer: 3, explanation: "The Quran was revealed to Prophet Muhammad (PBUH) over 23 years." },
            { id: 8, text: "What is the name of the fast during the month of Ramadan?", options: ["Zakat", "Sawm", "Hajj", "Shahada"], correctAnswer: 1, explanation: "Sawm is the Arabic word for fasting." },
            { id: 9, text: "In which city was Prophet Muhammad (PBUH) born?", options: ["Madinah", "Jerusalem", "Makkah", "Cairo"], correctAnswer: 2, explanation: "Prophet Muhammad (PBUH) was born in Makkah in the year 570 CE." },
            { id: 10, text: "Which angel brought the revelation to Prophet Muhammad (PBUH)?", options: ["Mikail", "Israfil", "Jibril", "Azrail"], correctAnswer: 2, explanation: "Angel Jibril (Gabriel) brought the revelations from Allah." },
            { id: 51, text: "What is the collective name for the five daily prayers?", options: ["Zakat", "Salah", "Hajj", "Sawm"], correctAnswer: 1, explanation: "Salah refers to the five daily ritual prayers." },
            { id: 52, text: "Which day of the week is considered most significant for congregational prayer?", options: ["Saturday", "Sunday", "Friday", "Monday"], correctAnswer: 2, explanation: "Friday (Jummah) is the most significant day for communal prayer." },
            { id: 53, text: "What is the call to prayer called in Arabic?", options: ["Iqamah", "Adhan", "Khutbah", "Dua"], correctAnswer: 1, explanation: "The Adhan is the Islamic call to prayer." },
            { id: 54, text: "What do Muslims say before starting any good action?", options: ["Alhamdulillah", "Allahu Akbar", "Bismillah", "SubhanAllah"], correctAnswer: 2, explanation: "Bismillah (In the name of Allah) is said before starting any task." },
            { id: 55, text: "Which pillar involves a pilgrimage to Makkah?", options: ["Salah", "Zakat", "Hajj", "Shahada"], correctAnswer: 2, explanation: "Hajj is the pilgrimage to the holy city of Makkah." },
            { id: 56, text: "What is the Arabic word for God?", options: ["Rabb", "Allah", "Khaliq", "Malik"], correctAnswer: 1, explanation: "Allah is the Arabic name for the One God." },
            { id: 57, text: "Which language is the original text of the Quran in?", options: ["Persian", "Urdu", "Arabic", "Turkish"], correctAnswer: 2, explanation: "The Quran was revealed in the Arabic language." },
            { id: 58, text: "What is the phrase used to express gratitude to Allah?", options: ["MashaAllah", "Alhamdulillah", "Astaghfirullah", "JazakAllah"], correctAnswer: 1, explanation: "Alhamdulillah means 'All praise is due to Allah'." },
            { id: 59, text: "What is the name of the month in which Muslims fast?", options: ["Muharram", "Ramadan", "Shawwal", "Rajab"], correctAnswer: 1, explanation: "Fast is observed during the month of Ramadan." },
            { id: 60, text: "Who was the first man created by Allah?", options: ["Nuh", "Ibrahim", "Adam", "Musa"], correctAnswer: 2, explanation: "Prophet Adam (AS) was the first human and the first prophet." }
        ]
    },
    {
        level: 2,
        difficulty: 'Medium',
        questions: [
            { id: 11, text: "What was the name of Prophet Muhammad's (PBUH) first wife?", options: ["Aisha", "Khadija", "Hafsa", "Zaynab"], correctAnswer: 1, explanation: "Khadija (RA) was the first wife and the first person to embrace Islam." },
            { id: 12, text: "Which Sura is known as the 'Heart of the Quran'?", options: ["Al-Fatiha", "Al-Baqarah", "Yasin", "Al-Ikhlas"], correctAnswer: 2, explanation: "Surah Yasin is often referred to as the heart of the Quran." },
            { id: 13, text: "What is the meaning of the word 'Zakat'?", options: ["Prayer", "Fasting", "Purification", "Faith"], correctAnswer: 2, explanation: "Zakat literally means 'to purify' or 'to grow'." },
            { id: 14, text: "How many years did the revelation of the Quran take?", options: ["10", "23", "40", "63"], correctAnswer: 1, explanation: "The Quran was revealed over a period of 23 years." },
            { id: 15, text: "Who was the first Caliph of Islam?", options: ["Umar", "Uthman", "Ali", "Abu Bakr"], correctAnswer: 3, explanation: "Abu Bakr Al-Siddiq (RA) was the first Caliph after the Prophet (PBUH)." },
            { id: 16, text: "What is the name of the well located near the Kaaba?", options: ["Kawthar", "Zamzam", "Salsabil", "Tasnim"], correctAnswer: 1, explanation: "The Zamzam well is a miraculously generated source of water." },
            { id: 17, text: "Which prophet is known as 'Khalilullah' (Friend of Allah)?", options: ["Musa", "Isa", "Ibrahim", "Nuh"], correctAnswer: 2, explanation: "Prophet Ibrahim (AS) is called the Friend of Allah." },
            { id: 18, text: "What are the two main festivals in Islam?", options: ["Eid al-Fitr & Ashura", "Eid al-Adha & Mawlid", "Eid al-Fitr & Eid al-Adha", "Ramadan & Hajj"], correctAnswer: 2, explanation: "The two primary festivals are Eid al-Fitr and Eid al-Adha." },
            { id: 19, text: "In which month was the Quran first revealed?", options: ["Muharram", "Ramadan", "Rajab", "Shaban"], correctAnswer: 1, explanation: "The Quran was first revealed during the month of Ramadan on Laylat al-Qadr." },
            { id: 20, text: "How many Surahs are in the Quran?", options: ["100", "110", "114", "120"], correctAnswer: 2, explanation: "The Quran contains 114 Surahs (chapters)." },
            { id: 61, text: "What is the name of the Prophet's migration from Makkah to Madinah?", options: ["Hajj", "Hijra", "Isra", "Umrah"], correctAnswer: 1, explanation: "The migration is known as the Hijra." },
            { id: 62, text: "Which companion was known as Al-Faruq?", options: ["Abu Bakr", "Umar ibn al-Khattab", "Uthman ibn Affan", "Ali ibn Abi Talib"], correctAnswer: 1, explanation: "Prophet Muhammad (PBUH) gave Umar (RA) the title Al-Faruq (The One Who Distinguishes Truth from Falsehood)." },
            { id: 63, text: "How many times is Prophet Muhammad (PBUH) mentioned by name in the Quran?", options: ["4", "25", "10", "50"], correctAnswer: 0, explanation: "The name Muhammad is mentioned explicitly 4 times in the Quran." },
            { id: 64, text: "What is the largest Surah in the Quran?", options: ["Al-Imran", "Al-Ma'idah", "Al-Baqarah", "An-Nisa"], correctAnswer: 2, explanation: "Surah Al-Baqarah is the longest chapter in the Quran." },
            { id: 65, text: "What is the name of the city the Prophet (PBUH) migrated to?", options: ["Taif", "Yathrib", "Jerusalem", "Cairo"], correctAnswer: 1, explanation: "Yathrib was later renamed Madinat al-Nabi (City of the Prophet)." },
            { id: 66, text: "Which Sahabi was known as the 'First Mu'adhin'?", options: ["Umar", "Bilal ibn Rabah", "Abu Bakr", "Ali"], correctAnswer: 1, explanation: "Bilal ibn Rabah (RA) was the first person to give the Adhan." },
            { id: 67, text: "What is the Arabic word for the sayings and actions of the Prophet (PBUH)?", options: ["Quran", "Hadith", "Sunnah", "Both B and C"], correctAnswer: 3, explanation: "Both Hadith (sayings) and Sunnah (ways/actions) describe his life." },
            { id: 68, text: "How many sajdas (prostrations) are in a two-rakat prayer?", options: ["2", "4", "6", "8"], correctAnswer: 1, explanation: "There are two sajdas in each rakat." },
            { id: 69, text: "What is the name of the optional night prayer during Ramadan?", options: ["Witr", "Tahajjud", "Taraweeh", "Ishraq"], correctAnswer: 2, explanation: "Taraweeh is the special congregational prayer held at night in Ramadan." },
            { id: 70, text: "What is the name of the gate of Paradise for those who fast?", options: ["Ar-Rayyan", "Al-Muzdalifah", "As-Safa", "Al-Marwa"], correctAnswer: 0, explanation: "Ar-Rayyan is the special gate for those who observe fasts." }
        ]
    },
    {
        level: 3,
        difficulty: 'Hard',
        questions: [
            { id: 21, text: "Which prophet could speak to animals and jinns?", options: ["Dawud", "Sulaiman", "Yusuf", "Zakariyya"], correctAnswer: 1, explanation: "Prophet Sulaiman (AS) was granted the miracle of understanding animal languages." },
            { id: 22, text: "What was the name of the building the Prophet (PBUH) stayed in after Hijra?", options: ["Quba", "Masjid an-Nabawi", "House of Abu Ayyub al-Ansari", "House of Abu Bakr"], correctAnswer: 2, explanation: "He stayed at the house of Abu Ayyub al-Ansari (RA) when he reached Madinah." },
            { id: 23, text: "Which battle was the first major conflict between Muslims and Quraysh?", options: ["Uhud", "Khandaq", "Badr", "Khaybar"], correctAnswer: 2, explanation: "The Battle of Badr was the first major battle in Islamic history." },
            { id: 24, text: "Who is known as the 'Sword of Allah' (Saifullah)?", options: ["Umar ibn al-Khattab", "Khalid ibn al-Walid", "Hamza ibn Abdul-Muttalib", "Ali ibn Abi Talib"], correctAnswer: 1, explanation: "Khalid ibn al-Walid (RA) was given this title by the Prophet (PBUH)." },
            { id: 25, text: "What is the name of the mountain where the first revelation occurred?", options: ["Mount Safa", "Mount Uhud", "Mount Hira (Jabal an-Nour)", "Mount Arafat"], correctAnswer: 2, explanation: "The first revelation happened in the Cave of Hira on Jabal an-Nour." },
            { id: 26, text: "Which prophet was swallowed by a large fish/whale?", options: ["Nuh", "Yunus", "Lut", "Hud"], correctAnswer: 1, explanation: "Prophet Yunus (AS) was swallowed by a whale and remained in its belly." },
            { id: 27, text: "How many gates are there in Jannah (Paradise)?", options: ["4", "7", "8", "9"], correctAnswer: 2, explanation: "According to Hadith, Jannah has eight gates." },
            { id: 28, text: "Who was the first person to call the Adhan (Mu'adhin)?", options: ["Abu Bakr", "Bilal ibn Rabah", "Umar ibn al-Khattab", "Zayd ibn Harithah"], correctAnswer: 1, explanation: "Bilal ibn Rabah (RA) was the first Mu'adhin in Islam." },
            { id: 29, text: "Which Surah does not start with 'Bismillah'?", options: ["Surah At-Tawbah", "Surah Al-Namal", "Surah Al-Alaq", "Surah Al-Fatiha"], correctAnswer: 0, explanation: "Surah At-Tawbah is the only Surah that does not begin with Bismillah." },
            { id: 30, text: "Name the uncle of the Prophet (PBUH) who was martyred in the Battle of Uhud.", options: ["Abu Talib", "Abbas", "Hamza", "Abu Lahab"], correctAnswer: 2, explanation: "Hamza ibn Abdul-Muttalib (RA), the Lion of Allah, was martyred at Uhud." },
            { id: 71, text: "What was the name of the Prophet's grandfather who looked after him?", options: ["Abu Talib", "Abdul Muttalib", "Abu Lahab", "Hamza"], correctAnswer: 1, explanation: "Abdul Muttalib took care of the Prophet (PBUH) after his mother passed away." },
            { id: 72, text: "Which prophet was known for his extreme patience during trials and illness?", options: ["Yusuf", "Ayyub", "Dhul-Kifl", "Isma'il"], correctAnswer: 1, explanation: "Prophet Ayyub (AS) is the archetype of patience in Islamic tradition." },
            { id: 73, text: "What is the name of the night journey of the Prophet from Makkah to Jerusalem?", options: ["Mi'raj", "Hijra", "Isra", "Umrah"], correctAnswer: 2, explanation: "Isra is the night journey to Jerusalem; Mi'raj is the ascent to heaven." },
            { id: 74, text: "Which angel is responsible for blowing the trumpet on Judgment Day?", options: ["Jibril", "Mikail", "Israfil", "Malik"], correctAnswer: 2, explanation: "Angel Israfil will blow the trumpet (Sūr) to signal the end of the world." },
            { id: 75, text: "What was the first capital of the Islamic Caliphate?", options: ["Makkah", "Madinah", "Kufa", "Damascus"], correctAnswer: 1, explanation: "Madinah was the administrative center during the Prophet's time and the early Caliphs." },
            { id: 76, text: "Who was accompanied by the Prophet (PBUH) during the migration (Hijra)?", options: ["Umar", "Ali", "Abu Bakr", "Uthman"], correctAnswer: 2, explanation: "Abu Bakr (RA) was his companion in the cave of Thawr." },
            { id: 77, text: "Which queen of Sheba balanced power and faith after meeting Prophet Sulaiman (AS)?", options: ["Asiya", "Bilqis", "Maryam", "Zulaykha"], correctAnswer: 1, explanation: "Queen Bilqis embraced Islam after visiting Prophet Sulaiman (AS)." },
            { id: 78, text: "What is the name of the field where the main ritual of Hajj takes place?", options: ["Mina", "Muzdalifah", "Arafat", "Safa"], correctAnswer: 2, explanation: "Standing at Arafat is the most essential element of Hajj." },
            { id: 79, text: "How many Sahaba participated in the Battle of Badr?", options: ["313", "1000", "1500", "70"], correctAnswer: 0, explanation: "The Muslim army at Badr consisted of approximately 313 companions." },
            { id: 80, text: "Which daughter of the Prophet (PBUH) was married to Ali (RA)?", options: ["Zaynab", "Ruqayyah", "Umm Kulthum", "Fatimah"], correctAnswer: 3, explanation: "Fatimah (RA) was the youngest daughter and wife of Ali (RA)." }
        ]
    },
    {
        level: 4,
        difficulty: 'Expert',
        questions: [
            { id: 31, text: "Who wrote down the revelation 'Wahy' for the Prophet (PBUH)?", options: ["Zayd ibn Thabit", "Uthman ibn Affan", "Ali ibn Abi Talib", "All of the above"], correctAnswer: 3, explanation: "Many companions like Zayd, Uthman, and Ali served as scribes of the revelation." },
            { id: 32, text: "What was the original number of daily prayers commanded during Isra and Mi'raj?", options: ["5", "10", "50", "100"], correctAnswer: 2, explanation: "Initial command was 50 prayers, which was reduced to 5 through Prophet Musa's advice." },
            { id: 33, text: "Which treaty was signed between the Muslims and the Quraysh in 6 AH?", options: ["Treaty of Madinah", "Treaty of Hudaibiyah", "Treaty of Taif", "Treaty of Aqaba"], correctAnswer: 1, explanation: "The Treaty of Hudaibiyah was a pivotal 10-year peace agreement." },
            { id: 34, text: "Which Sahabi is known as 'Dhun-Nurayn' (Possessor of two lights)?", options: ["Abu Bakr", "Umar", "Uthman", "Ali"], correctAnswer: 2, explanation: "Uthman (RA) was given this title because he married two of the Prophet's daughters." },
            { id: 35, text: "How many Sajdah (prostration) marks are there in the Quran?", options: ["10", "14", "15", "11"], correctAnswer: 2, explanation: "There are 15 points in the Quran where prostration is required according to most scholars." },
            { id: 36, text: "What was the name of the horse-like creature the Prophet (PBUH) rode during Mi'raj?", options: ["Qaswa", "Buraq", "Duldul", "Adha"], correctAnswer: 1, explanation: "The Buraq carried the Prophet (PBUH) from Makkah to Jerusalem and heaven." },
            { id: 37, text: "Who was the king of Abyssinia (Najashi) who protected the first Muslim migrants?", options: ["Ashama ibn Abjar", "Heraclius", "Chosroes", "Muqawqis"], correctAnswer: 0, explanation: "King Ashama (Najashi) was a just Christian king who later embraced Islam." },
            { id: 38, text: "In which year did the Conquest of Makkah take place?", options: ["6 AH", "8 AH", "10 AH", "2 AH"], correctAnswer: 1, explanation: "Makkah was conquered peacefully by the Muslims in 8 AH (630 CE)." },
            { id: 39, text: "Which Surah mentions the story of the 'People of the Cave'?", options: ["Al-Baqarah", "Yasin", "Al-Kahf", "Al-Anbiya"], correctAnswer: 2, explanation: "Surah Al-Kahf details the story of the youth who slept for centuries in a cave." },
            { id: 40, text: "What is the name of the bridge over Hell that leads to Paradise?", options: ["Sirat", "Mizan", "Haud", "Kauthar"], correctAnswer: 0, explanation: "The As-Sirat is the bridge that every person must cross on Judgment Day." },
            { id: 81, text: "Which Sahabi was known as the 'Translator of the Quran' (Tarjuman al-Quran)?", options: ["Abdullah ibn Mas'ud", "Abdullah ibn Abbas", "Abdullah ibn Umar", "Abdullah ibn Amr"], correctAnswer: 1, explanation: "Abdullah ibn Abbas (RA) was highly knowledgeable in Tafsir." },
            { id: 82, text: "What was the name of the Prophet's mother?", options: ["Halima", "Aminah", "Barakah", "Fatima"], correctAnswer: 1, explanation: "Aminah bint Wahb was the mother of Prophet Muhammad (PBUH)." },
            { id: 83, text: "Which Surah is also known as 'Umm al-Kitab'?", options: ["Al-Baqarah", "Al-Fatiha", "Al-Ikhlas", "Yasin"], correctAnswer: 1, explanation: "Surah Al-Fatiha is known as the 'Mother of the Book'." },
            { id: 84, text: "In which century CE did the Prophet (PBUH) live?", options: ["5th", "6th", "7th", "8th"], correctAnswer: 2, explanation: "He lived from 570 to 632 CE, primarily in the 7th century." },
            { id: 85, text: "What was the name of the first mosque built by the Prophet (PBUH)?", options: ["Masjid an-Nabawi", "Masjid al-Haram", "Quba Mosque", "Masjid al-Aqsa"], correctAnswer: 2, explanation: "The Quba Mosque near Madinah was the first mosque built by the Prophet." },
            { id: 86, text: "Who was the maternal grandfather of the Prophet (PBUH)?", options: ["Wahb ibn 'Abd Manaf", "Hashim", "Qusai", "Kilab"], correctAnswer: 0, explanation: "Wahb ibn 'Abd Manaf was the father of Aminah." },
            { id: 87, text: "Which prophet is mentioned as 'Dhun-Nun' in the Quran?", options: ["Yusuf", "Zakariyya", "Yunus", "Lut"], correctAnswer: 2, explanation: "Dhun-Nun means 'Owner of the Fish', referring to Prophet Yunus (AS)." },
            { id: 88, text: "What is the term for a Hadith that is traced back to Allah directly?", options: ["Sahih", "Hasan", "Qudsi", "Mutawatir"], correctAnswer: 2, explanation: "A Hadith Qudsi is one where the Prophet (PBUH) narrates from Allah." },
            { id: 89, text: "During which caliphate was the Quran first compiled into a single book?", options: ["Abu Bakr", "Umar", "Uthman", "Ali"], correctAnswer: 0, explanation: "Abu Bakr (RA) initiated the first compilation after the Battle of Yamama." },
            { id: 90, text: "What was the name of the battle in which the Prophet's tooth was broken?", options: ["Badr", "Uhud", "Khandaq", "Tabuk"], correctAnswer: 1, explanation: "At the Battle of Uhud, the Prophet (PBUH) sustained several injuries." }
        ]
    },
    {
        level: 5,
        difficulty: 'Master',
        questions: [
            { id: 41, text: "Which companion was referred to by the Prophet (PBUH) as the 'Governor of the Ummah'?", options: ["Abu Ubaidah ibn al-Jarrah", "Sa'd ibn Abi Waqqas", "Abdur-Rahman ibn Awf", "Talha ibn Ubaidullah"], correctAnswer: 0, explanation: "The Prophet (PBUH) called Abu Ubaidah (RA) 'Amin al-Ummah' (Trustworthy of the Ummah)." },
            { id: 42, text: "What was the name of the camel the Prophet (PBUH) rode during the Hijra?", options: ["Al-Adba", "Al-Qaswa", "Al-Jada", "Al-Wajna"], correctAnswer: 1, explanation: "Al-Qaswa was the Prophet's (PBUH) favorite and most famous camel." },
            { id: 43, text: "Which Sahabi was known as the 'Secret Keeper' of the Prophet (PBUH)?", options: ["Hudhayfah ibn al-Yaman", "Muadh ibn Jabal", "Abu Hurairah", "Anas ibn Malik"], correctAnswer: 0, explanation: "Hudhayfah (RA) knew the names of the hypocrites given to him by the Prophet (PBUH)." },
            { id: 44, text: "In which year did the Battle of Khaybar occur?", options: ["5 AH", "6 AH", "7 AH", "8 AH"], correctAnswer: 2, explanation: "The Battle of Khaybar took place in 7 AH." },
            { id: 45, text: "Which prophet is mentioned most frequently by name in the Quran?", options: ["Muhammad (PBUH)", "Ibrahim (AS)", "Musa (AS)", "Isa (AS)"], correctAnswer: 2, explanation: "Prophet Musa (AS) is mentioned 136 times in the Quran." },
            { id: 46, text: "What was the name of the agreement between the Prophet (PBUH) and the people of Madinah?", options: ["Covenant of Madinah", "Charter of Madinah", "Pledge of Aqaba", "Constitution of Madinah"], correctAnswer: 3, explanation: "The Constitution of Madinah was the first written constitution in the world." },
            { id: 47, text: "Who was the leader of the hypocrites in Madinah during the Prophet's time?", options: ["Abu Jahl", "Abu Lahab", "Abdullah ibn Ubayy", "Musaylima"], correctAnswer: 2, explanation: "Abdullah ibn Ubayy ibn Salul was the primary leader of the Monafiqeen." },
            { id: 48, text: "Which Sahabi did the Prophet (PBUH) send as the first teacher to Madinah?", options: ["Zayd ibn Thabit", "Mus'ab ibn 'Umair", "Muadh ibn Jabal", "Abdullah ibn Mas'ud"], correctAnswer: 1, explanation: "Mus'ab ibn 'Umair (RA) was sent after the first Pledge of Aqaba." },
            { id: 49, text: "What does 'Al-Mu'awwidhatayn' refer to?", options: ["Surah Ikhlas & Falaq", "Surah Falaq & Nas", "Surah Ikhlas & Nas", "Surah Fatiha & Ikhlas"], correctAnswer: 1, explanation: "It refers to the two Surahs for seeking protection (Falaq and Nas)." },
            { id: 50, text: "Which Sura is equivalent to one-third of the Quran?", options: ["Al-Fatiha", "Al-Ikhlas", "Al-Kafirun", "Al-Mulk"], correctAnswer: 1, explanation: "Prophet Muhammad (PBUH) said Surah Al-Ikhlas is equivalent to a third of the Quran." },
            { id: 91, text: "How many companions are known as the 'Ten Promised Paradise' (Al-Ashara al-Mubashara)?", options: ["5", "10", "12", "7"], correctAnswer: 1, explanation: "The Prophet (PBUH) listed ten specific companions as being in Paradise." },
            { id: 92, text: "Which prophet had a dream of eleven stars, the sun, and the moon prostrating to him?", options: ["Ibrahim", "Isma'il", "Yusuf", "Ya'qub"], correctAnswer: 2, explanation: "This dream of Prophet Yusuf (AS) is mentioned in Surah Yusuf." },
            { id: 93, text: "What was the name of the Christian monk who recognized the Prophet (PBUH) as a child?", options: ["Waraqa", "Bahira", "Nestorius", "Addas"], correctAnswer: 1, explanation: "Bahira saw the seal of prophethood during a trade journey to Syria." },
            { id: 94, text: "In which year of the Hijra was the direction of Qibla changed from Jerusalem to Makkah?", options: ["1 AH", "2 AH", "3 AH", "4 AH"], correctAnswer: 1, explanation: "The change occurred approximately 17 months after the Hijra." },
            { id: 95, text: "Name the Sahabi who narrated the highest number of Hadith.", options: ["Aisha", "Abdullah ibn Umar", "Abu Hurairah", "Anas ibn Malik"], correctAnswer: 2, explanation: "Abu Hurairah (RA) narrated over 5,000 hadiths." },
            { id: 96, text: "Which prophet was given the miracle of the 'White Hand' and the 'Staff'?", options: ["Isa", "Musa", "Sulaiman", "Ibrahim"], correctAnswer: 1, explanation: "These were two of the nine major signs given to Prophet Musa (AS)." },
            { id: 97, text: "What was the depth of the trench in the Battle of the Trench (Khandaq)?", options: ["1 meter", "3 meters", "5 meters", "10 meters"], correctAnswer: 1, explanation: "Historical secondary sources suggest it was about 3-4 meters deep and 4-5 meters wide." },
            { id: 98, text: "Who was the commander of the Muslim army at the Battle of Yarmouk?", options: ["Umar", "Khalid ibn al-Walid", "Abu Ubaidah", "Sa'd ibn Abi Waqqas"], correctAnswer: 1, explanation: "Khalid ibn al-Walid (RA) led the forces in this decisive victory against the Byzantines." },
            { id: 99, text: "Which prophet's people were destroyed by a continuous howling wind for seven nights?", options: ["Thamud", "Ad", "Madyan", "Sodom"], correctAnswer: 1, explanation: "The people of 'Ad (Prophet Hud's people) were destroyed by a fierce wind." },
            { id: 100, text: "In which Surah is the story of 'Dhul-Qarnayn' mentioned?", options: ["Al-Kahf", "Al-Hajj", "Al-Qisas", "Al-Furqan"], correctAnswer: 0, explanation: "The travels of Dhul-Qarnayn are detailed in Surah Al-Kahf." }
        ]
    }
];
