import { NameOfAllah } from './memory.model';

export const NAMES_OF_ALLAH: NameOfAllah[] = [
    { id: 1, arabic: "الرحمن", transliteration: "Ar-Rahman", english: "The Entirely Merciful" },
    { id: 2, arabic: "الرحيم", transliteration: "Ar-Raheem", english: "The Especially Merciful" },
    { id: 3, arabic: "الملك", transliteration: "Al-Malik", english: "The Sovereign Lord" },
    { id: 4, arabic: "القدوس", transliteration: "Al-Quddus", english: "The Holy" },
    { id: 5, arabic: "السلام", transliteration: "As-Salam", english: "The Source of Peace" },
    { id: 6, arabic: "المؤمن", transliteration: "Al-Mu'min", english: "The Guardian of Faith" },
    { id: 7, arabic: "المهيمن", transliteration: "Al-Muhaymin", english: "The Protector" },
    { id: 8, arabic: "العزيز", transliteration: "Al-Aziz", english: "The Mighty" },
    { id: 9, arabic: "الجبار", transliteration: "Al-Jabbar", english: "The Compeller" },
    { id: 10, arabic: "المتكبر", transliteration: "Al-Mutakabbir", english: "The Majestic" },
    { id: 11, arabic: "الخالق", transliteration: "Al-Khaliq", english: "The Creator" },
    { id: 12, arabic: "البارئ", transliteration: "Al-Bari'", english: "The Evolver" },
    { id: 13, arabic: "المصور", transliteration: "Al-Musawwir", english: "The Fashioner" },
    { id: 14, arabic: "الغفار", transliteration: "Al-Ghaffar", english: "The Forgiver" },
    { id: 15, arabic: "القهار", transliteration: "Al-Qahhar", english: "The Subduer" },
    { id: 16, arabic: "الوهاب", transliteration: "Al-Wahhab", english: "The Bestower" },
    { id: 17, arabic: "الرزاق", transliteration: "Ar-Razzaq", english: "The Provider" },
    { id: 18, arabic: "الفتاح", transliteration: "Al-Fattah", english: "The Opener" },
    { id: 19, arabic: "العليم", transliteration: "Al-Alim", english: "The All-Knowing" },
    { id: 20, arabic: "القابض", transliteration: "Al-Qabid", english: "The Constrictor" },
    { id: 21, arabic: "الباسط", transliteration: "Al-Basit", english: "The Expander" },
    { id: 22, arabic: "الخافض", transliteration: "Al-Khafid", english: "The Abaser" },
    { id: 23, arabic: "الرافع", transliteration: "Ar-Rafi", english: "The Exalter" },
    { id: 24, arabic: "المعز", transliteration: "Al-Mu'izz", english: "The Giver of Honor" },
    { id: 25, arabic: "المذل", transliteration: "Al-Mudhill", english: "The Giver of Dishonor" },
    { id: 26, arabic: "السميع", transliteration: "As-Sami", english: "The All-Hearing" },
    { id: 27, arabic: "البصير", transliteration: "Al-Basir", english: "The All-Seeing" },
    { id: 28, arabic: "الحكم", transliteration: "Al-Hakam", english: "The Judge" },
    { id: 29, arabic: "العدل", transliteration: "Al-Adl", english: "The Utterly Just" },
    { id: 30, arabic: "اللطيف", transliteration: "Al-Latif", english: "The Subtle One" },
    { id: 31, arabic: "الخبير", transliteration: "Al-Khabir", english: "The All-Aware" },
    { id: 32, arabic: "الحليم", transliteration: "Al-Halim", english: "The Forbearing" },
    { id: 33, arabic: "العظيم", transliteration: "Al-Azim", english: "The Magnificent" },
    { id: 34, arabic: "الغفور", transliteration: "Al-Ghafur", english: "The All-Forgiving" },
    { id: 35, arabic: "الشكور", transliteration: "Ash-Shakur", english: "The Appreciative" },
    { id: 36, arabic: "العلي", transliteration: "Al-Ali", english: "The Most High" },
    { id: 37, arabic: "الكبير", transliteration: "Al-Kabir", english: "The Most Great" },
    { id: 38, arabic: "الحفيظ", transliteration: "Al-Hafiz", english: "The Preserver" },
    { id: 39, arabic: "المقيت", transliteration: "Al-Muqit", english: "The Sustainer" },
    { id: 40, arabic: "الحسيب", transliteration: "Al-Hasib", english: "The Reckoner" },
    { id: 41, arabic: "الجليل", transliteration: "Al-Jalil", english: "The Sublime One" },
    { id: 42, arabic: "الكريم", transliteration: "Al-Karim", english: "The Generous One" },
    { id: 43, arabic: "الرقيب", transliteration: "Ar-Raqib", english: "The Watchful" },
    { id: 44, arabic: "المجيب", transliteration: "Al-Mujib", english: "The Responsive" },
    { id: 45, arabic: "الواسع", transliteration: "Al-Wasi", english: "The All-Pervading" },
    { id: 46, arabic: "الحكيم", transliteration: "Al-Hakim", english: "The Wise" },
    { id: 47, arabic: "الودود", transliteration: "Al-Wadud", english: "The Loving" },
    { id: 48, arabic: "المجيد", transliteration: "Al-Majid", english: "The Most Glorious" },
    { id: 49, arabic: "الباعث", transliteration: "Al-Baith", english: "The Resurrector" },
    { id: 50, arabic: "الشهيد", transliteration: "Ash-Shahid", english: "The Witness" },
    { id: 51, arabic: "الحق", transliteration: "Al-Haqq", english: "The Truth" },
    { id: 52, arabic: "الوكيل", transliteration: "Al-Wakil", english: "The Trustee" },
    { id: 53, arabic: "القوي", transliteration: "Al-Qawwi", english: "The Most Strong" },
    { id: 54, arabic: "المتين", transliteration: "Al-Matin", english: "The Firm One" },
    { id: 55, arabic: "الولي", transliteration: "Al-Wali", english: "The Protecting Friend" },
    { id: 56, arabic: "الحميد", transliteration: "Al-Hamid", english: "The Praiseworthy" },
    { id: 57, arabic: "المحصي", transliteration: "Al-Muhsi", english: "The Accounter" },
    { id: 58, arabic: "المبدئ", transliteration: "Al-Mubdi'", english: "The Originator" },
    { id: 59, arabic: "المعيد", transliteration: "Al-Mu'id", english: "The Restorer" },
    { id: 60, arabic: "المحيي", transliteration: "Al-Muhyi", english: "The Giver of Life" },
    { id: 61, arabic: "المميت", transliteration: "Al-Mumit", english: "The Creator of Death" },
    { id: 62, arabic: "الحي", transliteration: "Al-Hayy", english: "The Alive" },
    { id: 63, arabic: "القيوم", transliteration: "Al-Qayyum", english: "The Self-Subsisting" },
    { id: 64, arabic: "الواجد", transliteration: "Al-Wajid", english: "The Perceiver" },
    { id: 65, arabic: "الماجد", transliteration: "Al-Majid", english: "The Illustrious" },
    { id: 66, arabic: "الواحد", transliteration: "Al-Wahid", english: "The Unique" },
    { id: 67, arabic: "الاحد", transliteration: "Al-Ahad", english: "The One" },
    { id: 68, arabic: "الصمد", transliteration: "As-Samad", english: "The Eternal" },
    { id: 69, arabic: "القادر", transliteration: "Al-Qadir", english: "The Able" },
    { id: 70, arabic: "المقتدر", transliteration: "Al-Muqtadir", english: "The Powerful" },
    { id: 71, arabic: "المقدم", transliteration: "Al-Muqaddim", english: "The Expediter" },
    { id: 72, arabic: "المؤخر", transliteration: "Al-Mu'akhkhir", english: "The Delayer" },
    { id: 73, arabic: "الأول", transliteration: "Al-Awwal", english: "The First" },
    { id: 74, arabic: "الأخير", transliteration: "Al-Akhir", english: "The Last" },
    { id: 75, arabic: "الظاهر", transliteration: "Az-Zahir", english: "The Manifest" },
    { id: 76, arabic: "الباطن", transliteration: "Al-Batin", english: "The Hidden" },
    { id: 77, arabic: "الوالي", transliteration: "Al-Wali", english: "The Governor" },
    { id: 78, arabic: "المتعالي", transliteration: "Al-Muta'ali", english: "The Most Exalted" },
    { id: 79, arabic: "البر", transliteration: "Al-Barr", english: "The Source of Goodness" },
    { id: 80, arabic: "التواب", transliteration: "At-Tawwab", english: "The Acceptor of Repentance" },
    { id: 81, arabic: "المنتقم", transliteration: "Al-Muntaqim", english: "The Avenger" },
    { id: 82, arabic: "العفو", transliteration: "Al-Afu", english: "The Pardoner" },
    { id: 83, arabic: "الرؤوف", transliteration: "Ar-Ra'uf", english: "The Compassionate" },
    { id: 84, arabic: "مالك الملك", transliteration: "Malik-ul-Mulk", english: "The Eternal Owner of Sovereignty" },
    { id: 85, arabic: "ذو الجلال والإكرام", transliteration: "Dhul-Jalal-wal-Ikram", english: "The Lord of Majesty and Bounty" },
    { id: 86, arabic: "المقسط", transliteration: "Al-Muqsit", english: "The Equitable" },
    { id: 87, arabic: "الجامع", transliteration: "Al-Jami", english: "The Gatherer" },
    { id: 88, arabic: "الغني", transliteration: "Al-Ghani", english: "The Self-Sufficient" },
    { id: 89, arabic: "المغني", transliteration: "Al-Mughni", english: "The Enricher" },
    { id: 90, arabic: "المانع", transliteration: "Al-Mani", english: "The Preventer" },
    { id: 91, arabic: "الضار", transliteration: "Ad-Darr", english: "The Distressful" },
    { id: 92, arabic: "النافع", transliteration: "An-Nafi", english: "The Propitious" },
    { id: 93, arabic: "النور", transliteration: "An-Nur", english: "The Light" },
    { id: 94, arabic: "الهادي", transliteration: "Al-Hadi", english: "The Guide" },
    { id: 95, arabic: "البديع", transliteration: "Al-Badi", english: "The Incomparable" },
    { id: 96, arabic: "الباقي", transliteration: "Al-Baqi", english: "The Everlasting" },
    { id: 97, arabic: "الوارث", transliteration: "Al-Warith", english: "The Supreme Inheritor" },
    { id: 98, arabic: "الرشيد", transliteration: "Ar-Rashid", english: "The Guide to Right Path" },
    { id: 99, arabic: "الصبور", transliteration: "As-Sabur", english: "The Patient" }
];
