import { WordSearchLevel } from './word-search.model';

export const WORD_SEARCH_LEVELS: WordSearchLevel[] = [
    {
        id: 1,
        title: 'The Basics',
        description: 'Common Islamic terms.',
        gridSize: 10,
        words: [
            { arabic: 'الله', english: 'Allah', meaning: 'God' },
            { arabic: 'محمد', english: 'Muhammad', meaning: 'The Prophet' },
            { arabic: 'إسلام', english: 'Islam', meaning: 'Submission' },
            { arabic: 'قرآن', english: 'Quran', meaning: 'The Holy Book' },
            { arabic: 'صلاة', english: 'Salah', meaning: 'Prayer' },
            { arabic: 'إيمان', english: 'Iman', meaning: 'Faith' },
            { arabic: 'مسجد', english: 'Masjid', meaning: 'Mosque' },
            { arabic: 'أذان', english: 'Adhan', meaning: 'Call to Prayer' },
            { arabic: 'كعبة', english: 'Kaaba', meaning: 'Sacred House' },
            { arabic: 'مكة', english: 'Mecca', meaning: 'Holy City' },
            { arabic: 'مدينة', english: 'Medina', meaning: 'The City' },
            { arabic: 'حجاب', english: 'Hijab', meaning: 'Veil' },
            { arabic: 'تسبيح', english: 'Tasbih', meaning: 'Glorification' },
            { arabic: 'سنة', english: 'Sunnah', meaning: 'Tradition' },
            { arabic: 'حلال', english: 'Halal', meaning: 'Permissible' },
            { arabic: 'حرام', english: 'Haram', meaning: 'Forbidden' },
            { arabic: 'دعاء', english: 'Dua', meaning: 'Supplication' },
            { arabic: 'ذكر', english: 'Zikr', meaning: 'Remembrance' },
            { arabic: 'جنة', english: 'Jannah', meaning: 'Paradise' },
            { arabic: 'جهنم', english: 'Jahannam', meaning: 'Hellfire' }
        ]
    },
    {
        id: 2,
        title: 'Pillars & Worship',
        description: 'Key Islamic concepts.',
        gridSize: 10,
        words: [
            { arabic: 'شهادة', english: 'Shahada', meaning: 'Testimony' },
            { arabic: 'زكاة', english: 'Zakat', meaning: 'Charity' },
            { arabic: 'صوم', english: 'Sawm', meaning: 'Fasting' },
            { arabic: 'حج', english: 'Hajj', meaning: 'Pilgrimage' },
            { arabic: 'عمرة', english: 'Umrah', meaning: 'Lesser Pilgrimage' },
            { arabic: 'إحرام', english: 'Ihram', meaning: 'Sacred State' },
            { arabic: 'طواف', english: 'Tawaf', meaning: 'Circumambulation' },
            { arabic: 'صفا', english: 'Safa', meaning: 'Safa hill' },
            { arabic: 'مروة', english: 'Marwa', meaning: 'Marwa hill' },
            { arabic: 'عرفة', english: 'Arafat', meaning: 'Mount Arafat' },
            { arabic: 'جمرات', english: 'Jamarat', meaning: 'Stoning Pillars' },
            { arabic: 'عيد', english: 'Eid', meaning: 'Festival' },
            { arabic: 'رمضان', english: 'Ramadan', meaning: 'Holy Month' },
            { arabic: 'إفطار', english: 'Iftar', meaning: 'Breaking Fast' },
            { arabic: 'سحور', english: 'Suhoor', meaning: 'Pre-dawn Meal' },
            { arabic: 'تراويح', english: 'Tarawih', meaning: 'Night Prayer' },
            { arabic: 'فطرانة', english: 'Fitrana', meaning: 'Eid Charity' },
            { arabic: 'صدقة', english: 'Sadaqah', meaning: 'Voluntary Charity' },
            { arabic: 'نية', english: 'Niyyah', meaning: 'Intention' },
            { arabic: 'طهارة', english: 'Taharah', meaning: 'Purity' }
        ]
    },
    {
        id: 3,
        title: 'The Prophets',
        description: 'Names of the Prophets.',
        gridSize: 10,
        words: [
            { arabic: 'آدم', english: 'Adam', meaning: 'Adam (AS)' },
            { arabic: 'نوح', english: 'Nuh', meaning: 'Noah (AS)' },
            { arabic: 'إدريس', english: 'Idris', meaning: 'Enoch (AS)' },
            { arabic: 'هود', english: 'Hud', meaning: 'Hud (AS)' },
            { arabic: 'صالح', english: 'Salih', meaning: 'Salih (AS)' },
            { arabic: 'إبراهيم', english: 'Ibrahim', meaning: 'Abraham (AS)' },
            { arabic: 'لوط', english: 'Lut', meaning: 'Lot (AS)' },
            { arabic: 'إسماعيل', english: 'Ismail', meaning: 'Ishmael (AS)' },
            { arabic: 'إسحاق', english: 'Ishaq', meaning: 'Isaac (AS)' },
            { arabic: 'يعقوب', english: 'Yaqub', meaning: 'Jacob (AS)' },
            { arabic: 'يوسف', english: 'Yusuf', meaning: 'Joseph (AS)' },
            { arabic: 'أيوب', english: 'Ayub', meaning: 'Job (AS)' },
            { arabic: 'شعيب', english: 'Shuaib', meaning: 'Jethro (AS)' },
            { arabic: 'موسى', english: 'Musa', meaning: 'Moses (AS)' },
            { arabic: 'هارون', english: 'Harun', meaning: 'Aaron (AS)' },
            { arabic: 'داوود', english: 'Dawud', meaning: 'David (AS)' },
            { arabic: 'سليمان', english: 'Sulaiman', meaning: 'Solomon (AS)' },
            { arabic: 'يونس', english: 'Yunus', meaning: 'Jonah (AS)' },
            { arabic: 'زكريا', english: 'Zakariya', meaning: 'Zechariah (AS)' },
            { arabic: 'يحيى', english: 'Yahya', meaning: 'John (AS)' }
        ]
    },
    {
        id: 4,
        title: 'Beautiful Names',
        description: '99 Names of Allah (SWT).',
        gridSize: 11,
        words: [
            { arabic: 'الرحمن', english: 'Ar-Rahman', meaning: 'The Most Gracious' },
            { arabic: 'الرحيم', english: 'Ar-Rahim', meaning: 'The Most Merciful' },
            { arabic: 'الملك', english: 'Al-Malik', meaning: 'The King' },
            { arabic: 'القدوس', english: 'Al-Quddus', meaning: 'The Holy' },
            { arabic: 'السلام', english: 'As-Salam', meaning: 'The Peace' },
            { arabic: 'المؤمن', english: 'Al-Mu\'min', meaning: 'Guardian of Faith' },
            { arabic: 'المهيمن', english: 'Al-Muhaymin', meaning: 'The Protector' },
            { arabic: 'العزيز', english: 'Al-Aziz', meaning: 'The Almighty' },
            { arabic: 'الجبار', english: 'Al-Jabbar', meaning: 'The Compeller' },
            { arabic: 'المتكبر', english: 'Al-Mutakabbir', meaning: 'The Majestic' },
            { arabic: 'الخالق', english: 'Al-Khaliq', meaning: 'The Creator' },
            { arabic: 'البارئ', english: 'Al-Bari', meaning: 'The Evolver' },
            { arabic: 'المصور', english: 'Al-Musawwir', meaning: 'The Fashioner' },
            { arabic: 'الغفار', english: 'Al-Ghaffar', meaning: 'The Forgiver' },
            { arabic: 'القهار', english: 'Al-Qahhar', meaning: 'The Subduer' },
            { arabic: 'الوهاب', english: 'Al-Wahhab', meaning: 'The Bestower' },
            { arabic: 'الرزاق', english: 'Al-Razzaq', meaning: 'The Provider' },
            { arabic: 'الفتاح', english: 'Al-Fattah', meaning: 'The Opener' },
            { arabic: 'العليم', english: 'Al-Alim', meaning: 'The All-Knowing' },
            { arabic: 'القابض', english: 'Al-Qabid', meaning: 'The Withholder' }
        ]
    }
];
